{
 "title": "Pod Troubleshooter",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Total (Cores)",
   "type": "timeseries",
   "description": "Total for all containers in Pod.\n\n1 = 1000 Millicores\n0.1 = 100 Millicores\n0.01 = 10 Millicores",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  container=\"$container\", \n  image!=\"\"\n}[$__rate_interval])\n",
     "legendFormat": "CPU Total"
    }
   ]
  },
  {
   "title": "CPU Throttling Ratio",
   "type": "timeseries",
   "description": "**CPU Quota:** Container limit on CPU usage).\n\n**CPU Scheduling Period:** Tiny chunks of time (usually every 100ms) - also see CPU CFS periods.\n\n**Throttled:** When container tries to use more CPU than allowed - Linux kernel stops container from using CPU for short time - (usually remainder of scheduling period).\n\n0–5%: normal, no concern\n\n5–10%: mild throttling, may be acceptable\n\n10–20%: moderate throttling, investigate if app is CPU-sensitive\n\n\\>20%: significant throttling, likely needs more CPU or tuning",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  container=\"$container\", \n  image!=\"\"\n}[$__rate_interval])\n/\nrate(container_cpu_cfs_periods_total{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  container=\"$container\", \n  image!=\"\"\n}[$__rate_interval])\n",
     "legendFormat": "CPU Throttled"
    }
   ]
  },
  {
   "title": "CPU Resource Requests/Limits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) / 1024^2 * 2",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) / 1024^2 * 2",
     "legendFormat": "CPU Request"
    }
   ]
  },
  {
   "title": "Memory Usage (Container)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  container=\"$container\"\n}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Maxed Memory (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_failcnt{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  container=\"$container\"\n}[$__rate_interval])",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}